### ISSUE TITLE
UnboundLocalError: local variable 't' referenced before assignment` on modelTrain.py

### ISSUE THREAD

**Issue by epolewski** [zzj0311/pytorch-image-inpainting-using-mixed-convolution#1]
-----------epoch 88 start here----------
-----------epoch 89 start here----------
-----------epoch 90 start here----------
-----------epoch 91 start here----------
-----------epoch 92 start here----------
-----------epoch 93 start here----------
-----------epoch 94 start here----------
-----------epoch 95 start here----------
-----------epoch 96 start here----------
-----------epoch 97 start here----------
-----------epoch 98 start here----------
-----------epoch 99 start here----------
Traceback (most recent call last):
  File "modelTrain.py", line 93, in <module>
    dSet_mean=dSet_mean, save_dir=args.save_dir)
  File "C:\Users\Eric\Downloads\pytorch-image-inpainting-using-mixed-convolution
-master\util.py", line 206, in train
    return loss_list, thetime / t
UnboundLocalError: local variable 't' referenced before assignment

**Comment by epolewski** [comment]
Seemed to be fixed by making sure there were at least 20-30 images in the dataset, but after the training is finished it doesn't create any of the folders the ModelTest.py asks for:

parser.add_argument('--Gpth', '-G', type=str, default='./modelSaveG/ckpt/final.pth')
parser.add_argument('--Opth', '-O', type=str, default='./modelSaveOrigin/ckpt/final.pth')
parser.add_argument('--Ppth', '-P', type=str, default='./modelSave3/ckpt/final.pth')

**Comment by zzj0311** [comment]
hmmm，as the default interval is set to 10 & batch size is 16... so you should at least have more than 160 images to get a validation output

**Comment by zzj0311** [comment]
@epolewski I'll close this issue for now as I haven't get further info for days, feel free to reopen it if you need further help.
